name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Development
      run: docker-compose -f "docker-compose.dev.yml" up  --build
    - name: Test Production
      run: docker-compose -f "docker-compose.prod.yml" up -d --build
